version: '3.9'
services:
  minha_base_de_dados_mysql:
# parte adicionada ao criar o arquivo .env (explica no final)    
    env_file: 
      - .env
    container_name: minha_base_de_dados_mysql
    hostname: minha_base_de_dados_mysql
    image: mysql:8
    restart: always
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./minha_base_de_dados_mysql:/var/lib/mysql
    ports:
      - 3306:3306


# Essa parte do código para criação do servidor MySQL 
# com dados de "usuário, servidor e senha" foi movida 
# para cima em "env_file", pois esse arquivo 
# "docker-compose.yml" vai ser enviado para o GitHub e
# ficará disponível para todos. Em outras palavras, é 
# uma forma de você guardar sua senha e dados pessoais
# e não compartilhar para todos (nesse caso, não preci-
# sava por ser um exemplo).

    # environment:
    #   MYSQL_ROOT_PASSWORD: senha
    #   MYSQL_DATABASE: base_de_dados
    #   MYSQL_USER: usuario
    #   MYSQL_PASSWORD: senha
    #   TZ: America/Sao_Paulo